# node port allows access to pods inside node externally
# without this you can't access kubernetes pod 
# on deploying this service, it will create a port where you can 
# access the pod.

apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80

